services:
  bitcoin-node:
    build: .
    container_name: ${CONTAINER_NAME:-bitcoin-core-node}
    restart: unless-stopped
    
    # Map the data directory to your external drive
    # Path is configured via .env file
    volumes:
      - ${BITCOIN_DATA_PATH}:/home/bitcoin/.bitcoin
      
    # Expose ports to host
    ports:
      - "${RPC_PORT:-8332}:8332"  # RPC port
      - "${P2P_PORT:-8333}:8333"  # P2P port (mainnet)
      
    # Environment variables for configuration
    environment:
      - BITCOIN_DATA=/home/bitcoin/.bitcoin
      
    # Optional: Set resource limits
    # Uncomment and adjust based on your system resources
    # deploy:
    #   resources:
    #     limits:
    #       memory: ${MEMORY_LIMIT:-4G}
    #       cpus: '${CPU_LIMIT:-2}'

  electrs:
    build:
      context: ./electrs
      dockerfile: Dockerfile
    container_name: ${ELECTRS_CONTAINER_NAME:-electrs-server}
    restart: unless-stopped
    
    # Depend on bitcoin-node service
    depends_on:
      - bitcoin-node
    
    # Map the electrs data directory and share Bitcoin data
    volumes:
      - ${ELECTRS_DATA_PATH}:/data/electrs
      # Share Bitcoin data directory so Electrs can access blockchain and RPC cookie
      - ${BITCOIN_DATA_PATH}:/data/bitcoin:ro
      
    # Electrs is accessible via Tor hidden service only (no clearnet exposure)
    # ports:
    #   - "${ELECTRS_RPC_PORT:-50001}:50001"
      
    # Environment variables
    environment:
      - ELECTRS_DATA=/data/electrs
      
    # Optional: Set resource limits for Electrs
    # Uncomment and adjust based on your system resources
    # deploy:
    #   resources:
    #     limits:
    #       memory: ${ELECTRS_MEMORY_LIMIT:-2G}
    #       cpus: '${ELECTRS_CPU_LIMIT:-1}'

